-- local catppuccin = require("catppuccin")
--
-- catppuccin.setup({
--   transparent_background = false,
--   term_colors = false,
--   styles = {
--     comments = "italic",
--     functions = "italic",
--     keywords = "italic",
--     strings = "NONE",
--     variables = "NONE",
--   },
--   integrations = {
--     treesitter = true,
--     native_lsp = {
--       enabled = true,
--       virtual_text = {
--         errors = "italic",
--         hints = "italic",
--         warnings = "italic",
--         information = "italic",
--       },
--       underlines = {
--         errors = "underline",
--         hints = "underline",
--         warnings = "underline",
--         information = "underline",
--       },
--     },
--     lsp_trouble = false,
--     lsp_saga = false,
--     gitgutter = false,
--     gitsigns = false,
--     telescope = false,
--     nvimtree = {
--       enabled = true,
--       show_root = true,
--     },
--     which_key = false,
--     indent_blankline = {
--       enabled = false,
--       colored_indent_levels = false,
--     },
--     dashboard = false,
--     neogit = false,
--     vim_sneak = false,
--     fern = false,
--     barbar = false,
--     bufferline = true,
--     markdown = false,
--     lightspeed = false,
--     ts_rainbow = true,
--     hop = false,
--   },
-- })
--
-- vim.cmd[[colorscheme catppuccin]]
--
-- -- vim.o.background = 'dark'
-- -- vim.cmd([[colorscheme gruvbox]])
--
--
--
--
 require('tokyonight').setup({
  style = 'night'
})

vim.cmd([[colorscheme tokyonight]])
